# Test override - includes built-in Ollama service
# Environment variables are set directly here for test isolation
services:
  ollama:
    volumes:
      - ollama-data:/root/.ollama

  api:
    build:
      target: development
    ports: !override
      - "${HOST_BIND_IP}:${TEST_PORT}:8000"
    environment:
      - DATABASE_URL=sqlite:///data/sqlite_test.db
