# Development override - includes built-in Ollama service
# Environment variables are fixed for development (no .env override)
services:
  ollama:
    volumes:
      - ollama-data:/root/.ollama

  api:
    build:
      target: development
    ports: !override
      - "${HOST_BIND_IP}:${DEV_PORT}:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:///data/sqlite_dev.db
    volumes:
      - .:/app
      - /app/.venv
