# Development override - can be configured to use host Ollama for GPU acceleration
services:
  db:
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  # Ollama service - comment out this entire section to use host Ollama
  ollama:
    volumes:
      - ollama_data_dev:/root/.ollama

  api:
    build:
      target: runner
    volumes:
      - ./src:/app/src
      # Also mount alembic files for development
      - ./alembic:/app/alembic
      # Mount tests so they can be run inside the container if needed
      - ./tests:/app/tests
    # Use default entrypoint with modified worker count
    command: []
    # Uncomment the following for host Ollama (requires OLLAMA_HOST=http://host.docker.internal:11434)
    # depends_on:
    #   db:
    #     condition: service_healthy
    # environment:
    #   - OLLAMA_HOST=http://host.docker.internal:11434

volumes:
  postgres_data_dev:
    driver: local
  ollama_data_dev:
    driver: local
