# Test override - includes built-in Ollama service
# Environment variables are set directly here for test isolation
services:
  db:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_TEST_DB_NAME}" ]

  ollama:
    volumes:
      - ollama_data:/root/.ollama

  api:
    build:
      target: development
    ports:
      - "${HOST_BIND_IP}:${TEST_PORT}:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_TEST_DB_NAME}
      - POSTGRES_DB_NAME=${POSTGRES_TEST_DB_NAME}

