# Development override - includes built-in Ollama service
# Environment variables are fixed for development (no .env override)
services:
  db:
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  # Built-in Ollama service (always created for easy switching)
  ollama:
    image: ollama:latest
    build:
      context: ./ollama
      args:
        - BUILT_IN_OLLAMA_MODEL=${BUILT_IN_OLLAMA_MODEL}
    entrypoint: ollama
    command: serve
    volumes:
      - ollama_data_dev:/root/.ollama
    healthcheck:
      test: [ "CMD", "ollama", "list" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped

  api:
    build:
      target: production
    ports:
      - "${HOST_BIND_IP}:${DEV_PORT}:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/.venv
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_healthy
    # Environment variables are fixed for development isolation
    # Use default entrypoint and command from Dockerfile

volumes:
  postgres_data_dev:
    driver: local
  ollama_data_dev:
    driver: local
