# Test override - includes built-in Ollama service
# Environment variables are set directly here for test isolation
services:
  db:
    volumes:
      # Use separate test database volume
      - postgres_data_test:/var/lib/postgresql/data

  ollama:
    volumes:
      - ollama_data_test:/root/.ollama

  api:
    ports:
      - "${HOST_BIND_IP}:${TEST_PORT}:8000"

volumes:
  postgres_data_test:
    driver: local
  ollama_data_test:
    driver: local
