# Development override - includes built-in Ollama service
# Environment variables are fixed for development (no .env override)
services:
  db:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DEV_DB_NAME}" ]

  ollama:
    volumes:
      - ollama_data:/root/.ollama

  api:
    build:
      target: development
    ports:
      - "${HOST_BIND_IP}:${DEV_PORT}:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DEV_DB_NAME}
      - POSTGRES_DB_NAME=${POSTGRES_DEV_DB_NAME}
    volumes:
      - .:/app
      - /app/.venv

