# Development override - includes built-in Ollama service
# Environment variables are fixed for development (no .env override)
services:
  db:
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  ollama:
    volumes:
      - ollama_data_dev:/root/.ollama

  api:
    build:
      target: production
    ports:
      - "${HOST_BIND_IP}:${DEV_PORT}:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/.venv

volumes:
  postgres_data_dev:
    driver: local
  ollama_data_dev:
    driver: local
