"""Enhance Log model with details, prompt, and response

Revision ID: f4b34ce33c88
Revises: 66121df78c57
Create Date: 2025-08-23 06:50:25.810503

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f4b34ce33c88"
down_revision: Union[str, Sequence[str], None] = "66121df78c57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("logs", sa.Column("prompt", sa.Text(), nullable=True))
    op.add_column("logs", sa.Column("generated_response", sa.Text(), nullable=True))
    op.add_column("logs", sa.Column("error_details", sa.Text(), nullable=True))
    op.alter_column(
        "logs",
        "request_path",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.create_index(op.f("ix_logs_id"), "logs", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_logs_id"), table_name="logs")
    op.alter_column(
        "logs",
        "request_path",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_column("logs", "error_details")
    op.drop_column("logs", "generated_response")
    op.drop_column("logs", "prompt")
    # ### end Alembic commands ###
