name: E2E Tests

on:
  workflow_call:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'

      - name: Install and configure Poetry
        run: |
          pipx install poetry
          poetry config virtualenvs.in-project true

      - name: Setup environment and run E2E tests
        run: |
          make setup
          make e2e-test
