name: E2E Tests

on:
  workflow_call:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'

      - name: Setup environment
        run: make setup

      - name: Run E2E tests
        run: make e2e-test
