name: Format and Lint

on:
  workflow_call:

jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: make setup

      - name: Start containers
        run: make up

      - name: Run Ruff Linter
        run: make lint

      - name: Run Black Formatter Check
        run: make format-check

      - name: Cleanup containers
        if: always()
        run: make down
